version: '3'

volumes:
  data_volume:

services:

  gd_db:
    image: mysql
    env_file:
      - configs/common.env
    container_name: gd_db.mf
    restart: always
    tty: true
    ports:
      - 3666:3306
    volumes:
      - data_volume:/var/lib/mysql/
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - app-network

  gathering_app:
    container_name: gathering.mf
    build:
      context: .
      dockerfile: cmd/gathering/Dockerfile
      args:
        - GIT_COMMIT_HASH=$GIT_HASH
    restart: always
    ports:
      - 31115:31115
    depends_on:
      - gd_db
    networks:
      - app-network
    command: ["/app/wait-for-it.sh", "gd_db:3306", "--", "/app/gathering"]

  analyser_app:
    container_name: analyser.mf
    build:
      context: .
      dockerfile: cmd/analyser/Dockerfile
      args:
        - GIT_COMMIT_HASH=$GIT_HASH
    restart: always
    depends_on:
      - gathering_app
    ports:
      - 31116:31116
    networks:
      - app-network

#  dc_tarantool:
#    image: tarantool/tarantool
#    env_file:
#      - configs/common.env
#    container_name: gc_tnt.mf
#    volumes:
#      - ./scripts:/usr/local/share/tarantool/
#      #- data_volume:/var/lib/tarantool
#
#    command: tarantool /usr/local/share/tarantool/app.init.lua
#    networks:
#      - app-network
#    ports:
#      - 3999:3301
#    depends_on:
#      - gd_db

networks:
  app-network:
    driver: bridge