// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package repository

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson43905e23DecodeAnomalyDetectorInternalRepository(in *jlexer.Lexer, out *EventPreparedList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(EventPreparedList, 0, 2)
			} else {
				*out = EventPreparedList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 EventPrepared
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson43905e23EncodeAnomalyDetectorInternalRepository(out *jwriter.Writer, in EventPreparedList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v EventPreparedList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson43905e23EncodeAnomalyDetectorInternalRepository(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventPreparedList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson43905e23EncodeAnomalyDetectorInternalRepository(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventPreparedList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson43905e23DecodeAnomalyDetectorInternalRepository(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventPreparedList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson43905e23DecodeAnomalyDetectorInternalRepository(l, v)
}
func easyjson43905e23DecodeAnomalyDetectorInternalRepository1(in *jlexer.Lexer, out *EventPrepared) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "event_date":
			out.EventDate = string(in.String())
		case "entity_id":
			out.EntityID = int32(in.Int32())
		case "event_counter":
			out.EventCounter = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson43905e23EncodeAnomalyDetectorInternalRepository1(out *jwriter.Writer, in EventPrepared) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"event_date\":"
		out.RawString(prefix[1:])
		out.String(string(in.EventDate))
	}
	{
		const prefix string = ",\"entity_id\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntityID))
	}
	{
		const prefix string = ",\"event_counter\":"
		out.RawString(prefix)
		out.Int32(int32(in.EventCounter))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventPrepared) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson43905e23EncodeAnomalyDetectorInternalRepository1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventPrepared) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson43905e23EncodeAnomalyDetectorInternalRepository1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventPrepared) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson43905e23DecodeAnomalyDetectorInternalRepository1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventPrepared) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson43905e23DecodeAnomalyDetectorInternalRepository1(l, v)
}
