// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package gathering

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (PayloadMessage) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*PayloadMessage) UnmarshalJSON([]byte) error        { return nil }
func (PayloadMessage) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*PayloadMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PayloadMessage *PayloadMessage

func (StatRequestMessage) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*StatRequestMessage) UnmarshalJSON([]byte) error        { return nil }
func (StatRequestMessage) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*StatRequestMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_StatRequestMessage *StatRequestMessage
