// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package analyser

import (
	repository "anomaly_detector/internal/repository"
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE25a8b0DecodeAnomalyDetectorInternalRoutesAnalyser(in *jlexer.Lexer, out *Resp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ok":
			out.OK = bool(in.Bool())
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]repository.EventAnalysed, 0, 2)
					} else {
						out.Data = []repository.EventAnalysed{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v1 repository.EventAnalysed
					easyjsonE25a8b0DecodeAnomalyDetectorInternalRepository(in, &v1)
					out.Data = append(out.Data, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE25a8b0EncodeAnomalyDetectorInternalRoutesAnalyser(out *jwriter.Writer, in Resp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ok\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.OK))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Data {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjsonE25a8b0EncodeAnomalyDetectorInternalRepository(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Resp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE25a8b0EncodeAnomalyDetectorInternalRoutesAnalyser(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Resp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE25a8b0EncodeAnomalyDetectorInternalRoutesAnalyser(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Resp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE25a8b0DecodeAnomalyDetectorInternalRoutesAnalyser(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Resp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE25a8b0DecodeAnomalyDetectorInternalRoutesAnalyser(l, v)
}
func easyjsonE25a8b0DecodeAnomalyDetectorInternalRepository(in *jlexer.Lexer, out *repository.EventAnalysed) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "event_date":
			out.EventDate = string(in.String())
		case "entity_id":
			out.EntityID = int32(in.Int32())
		case "event_counter":
			out.EventCounter = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE25a8b0EncodeAnomalyDetectorInternalRepository(out *jwriter.Writer, in repository.EventAnalysed) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"event_date\":"
		out.RawString(prefix[1:])
		out.String(string(in.EventDate))
	}
	{
		const prefix string = ",\"entity_id\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntityID))
	}
	{
		const prefix string = ",\"event_counter\":"
		out.RawString(prefix)
		out.Int32(int32(in.EventCounter))
	}
	out.RawByte('}')
}
