app_port: 31116
auth_user: a
auth_token: b
conf_db:
  address: gd_db
  port: 3306
  user: g2jvD6L8CANDsYGhJBEyQYeEbmHj
  pass: ZTm0axdCQsrK1imCgsFq5KSAQZyzX2GhPpxr
  db_name: data_gather
  read_timeout: 1
  write_timeout: 1