// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package routes

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1f87d429DecodeAnomalyDetectorInternalRoutes(in *jlexer.Lexer, out *appInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ok":
			out.OK = bool(in.Bool())
		case "build_hash":
			out.BuildHash = string(in.String())
		case "build_time":
			out.BuildTime = string(in.String())
		case "app_name":
			out.AppName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1f87d429EncodeAnomalyDetectorInternalRoutes(out *jwriter.Writer, in appInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ok\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.OK))
	}
	{
		const prefix string = ",\"build_hash\":"
		out.RawString(prefix)
		out.String(string(in.BuildHash))
	}
	{
		const prefix string = ",\"build_time\":"
		out.RawString(prefix)
		out.String(string(in.BuildTime))
	}
	{
		const prefix string = ",\"app_name\":"
		out.RawString(prefix)
		out.String(string(in.AppName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v appInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1f87d429EncodeAnomalyDetectorInternalRoutes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v appInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1f87d429EncodeAnomalyDetectorInternalRoutes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *appInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1f87d429DecodeAnomalyDetectorInternalRoutes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *appInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1f87d429DecodeAnomalyDetectorInternalRoutes(l, v)
}
func easyjson1f87d429DecodeAnomalyDetectorInternalRoutes1(in *jlexer.Lexer, out *StatRequestMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "from":
			out.From = string(in.String())
		case "to":
			out.To = string(in.String())
		case "iterator":
			out.Iterator = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1f87d429EncodeAnomalyDetectorInternalRoutes1(out *jwriter.Writer, in StatRequestMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix[1:])
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	{
		const prefix string = ",\"iterator\":"
		out.RawString(prefix)
		out.Int32(int32(in.Iterator))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatRequestMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1f87d429EncodeAnomalyDetectorInternalRoutes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatRequestMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1f87d429EncodeAnomalyDetectorInternalRoutes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatRequestMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1f87d429DecodeAnomalyDetectorInternalRoutes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatRequestMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1f87d429DecodeAnomalyDetectorInternalRoutes1(l, v)
}
func easyjson1f87d429DecodeAnomalyDetectorInternalRoutes2(in *jlexer.Lexer, out *PayloadMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "label":
			out.Label = string(in.String())
		case "id":
			out.EntityID = int32(in.Int32())
		case "value":
			out.Value = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1f87d429EncodeAnomalyDetectorInternalRoutes2(out *jwriter.Writer, in PayloadMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix[1:])
		out.String(string(in.Label))
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		out.Int32(int32(in.EntityID))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Int32(int32(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PayloadMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1f87d429EncodeAnomalyDetectorInternalRoutes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PayloadMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1f87d429EncodeAnomalyDetectorInternalRoutes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PayloadMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1f87d429DecodeAnomalyDetectorInternalRoutes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PayloadMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1f87d429DecodeAnomalyDetectorInternalRoutes2(l, v)
}
